---
- name: Get Device Facts
  hosts: VMX
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    credentials:
      host: "{{ inventory_hostname }}"
      username: "lab"
      password: "lab123"

  tasks:
    - name: Retrieve facts from devices running Junos OS  
      juniper_junos_facts:  
        provider: "{{ credentials }}"
    - name: Print version
      debug:
        var: junos.version
